### ISSUE TITLE
Missing OAS documentation

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-write-api#11]
We should have a `/docs` (similar to http://demo-api.windingtree.com/docs) endpoint containing a reference documentation for the API in [OAS](https://github.com/OAI/OpenAPI-Specification). The documentation should be re-using data models from the [data model documentation](https://windingtree.github.io/docs/swagger-ui/) where possible.

**Comment by hynek-urban** [comment]
Implemented in the develop branch.
