### ISSUE TITLE
Support multiple swarm gateways

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-write-api#19]
We now rely on a single Swarm gateway. If that's offline or does not respond, the whole thing will break.

We should support fallback gateways.

Related to https://github.com/windingtree/off-chain-adapter-swarm/issues/8

**Comment by hynek-urban** [comment]
Is this still something that we want to do? Or are we content with the way this issue has been mitigated by #40?

**Comment by JirkaChadima** [comment]
I think this deals with a slightly different issue - i.e. configuration vs runtime. But you are correct that for now #40 might be enough. Let's close this and re-open if needed.
