### ISSUE TITLE
Infura API keys should not be publicly accessible (0sp)

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wt-write-api#23]
Currently, our Infura API key is publicly accessible within certain configurations (config/*.js). That should not be the case. The following steps need to be done:

1. Find a way to provide this key in a protected way, e.g. using encrypted variables in Travis.
2. Get a non-compromised Infura API key and utilize it according to point 1.
3. Disable the original API key.

**Comment by JirkaChadima** [comment]
`1.` resolved in 932e4fa

**Comment by JirkaChadima** [comment]
Changes in Infura API access: https://mailchi.mp/51860dca76fb/update-to-the-infura-api-authentication?e=1715cad57f + https://community.infura.io/t/is-it-ok-to-expose-my-infura-project-id-while-connecting-via-web3js-on-the-client-side/45

**Comment by czervenka** [comment]
@kvbik please, regenerate the api keys and pass it to @JirkaChadima

**Comment by kvbik** [comment]
PLAYGROUND id :: 5441ef93d3d248c7bd067e410110defa

**Comment by kvbik** [comment]
DEMO id :: dae17bcad1064150ad3b69ad8956cc81

**Comment by JirkaChadima** [comment]
Fixed in 5036b1825d78329dc063a1f8092d0b117809049d, will be deployed to AWS with the next version
