### ISSUE TITLE
Handle "replacement transaction underpriced"

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-write-api#42]
If ethereum node returns "replacement transaction underpriced", the API crashes with a 500. This happens when a user submits two transactions with the same ordinal number (i. e. the last submitted transaction was not yet mined).

I can see two possible approaches here:
1) Detect a pending transaction, and increment txid/nonce accordingly when needed before it gets submitted to a node. (Not sure if it's possible)
2) Transparently catch the error and tell the client what went wrong and that they should retry.

The first solution is more convenient for the users but not that transparent.

It's possible that we would need to update wt-js-libs code as well.

**Comment by JirkaChadima** [comment]
This is converted to a more friendly error in https://github.com/windingtree/wt-js-libs/commit/8c37d63707ea70645c2f0c24520e2a2ab044e95b

To mitigate this for now, we are at least exposing unrecognized error messages to clients after f5dd239.

**Comment by JirkaChadima** [comment]
This issue effectively prevents parallel usage of the API by the same account. Which sucks if you are managing multiple hotels.

There should be a way of [getting](https://github.com/ethereum/go-ethereum/issues/2880) number of pending transactions from the node, but it [does not work](https://github.com/ethereum/web3.js/issues/1741). The [alternative](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter) does not work against Infura nodes which we are currently using, because they [do not support filters](https://github.com/INFURA/infura/issues/13#issuecomment-272091360).

Since write-api is actually stateful, we might be able to keep track of pending tx's by ourselves. Which will decrease the probability of this issue happening but won't really make it go away, because the wallet associated with the account can be used to do transactions elsewhere.

**Comment by hynek-urban** [comment]
@JirkaChadima Not sure if I understand the issue correctly, but if you need to serialize certain requests, you can maybe draw some small inspiration from  WTAdapter.updateAvailability in the booking api. It's quite trivial, so maybe it doesn't add anything of value, but who knows.

**Comment by JirkaChadima** [comment]
@hynek-urban Yeah, I guess that's one way of doing it - and it looks pretty simple. But the issue is not overwriting the data out of order (which I think is what the code in booking-api is primarily dealing with), but parallel initialization of transactions. And since write-api actually knows about all the transactions that it initiated, it can do better then waiting for the transactions to be mined (~15 seconds) one by one. I'm not yet sure how reliable that can be, so maybe your solution will actually turn out to be the best one. We'll see. Thanks for pointing it out!

**Comment by hynek-urban** [comment]
@JirkaChadima After reading some more about Ethereum account nonces, it seems to me that the network will not process a transaction with a higher transaction ID until all the previous transactions (with lower nonces) have been processed, i.e., mined.

In other words, unless I misunderstand it, you'll have to wait for them to be mined one by one in any case.

**Comment by JirkaChadima** [comment]
So, from a lot of reading, the consensus probably is that it's not really a great idea of dealing with nonce tracking client-side. There are too many uncontrolled variables (txpool, pending txs in next block, invalid txs in txpool) that come into play. I decided to make the write-api transparently fail with 503 and `Retry-After` header with a value of `20`. That should give clients enough information on what went wrong and they should be able to recover. Dealt with in #52

Here are some relevant resources:

Interesting summary of the exact same problem: https://medium.com/kinblog/making-sense-of-ethereum-nonce-sense-3858d5588c64
Metamask's solution of tracking nonces client-side: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/nonce-tracker.js
