### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wt-write-api#7]
In the data strucure (https://windingtree.github.io/docs/swagger-ui/), there is a phone number in the contact component. However, it is of type "string" with no particular format or standard associated.

The question is - do we want to validate phone number on the API side? It could rather easily be done with the `node-phonenumber` npm package but it imposes certain format on the API user - do we want to do that?

**Comment by JirkaChadima** [comment]
I have used [this regex](https://github.com/windingtree/wt-hotel-explorer/blob/ca77cb33f6a4f1e0694087dce08bac2cbf9b15d6/src/components/BookingForm/index.jsx#L93) on the client side for phone validation. It seemed robust enough (for now). See https://www.regextester.com/1978 for examples. Not sure how compatible it is with `node-phonenumber` though.

**Comment by hynek-urban** [comment]
I think a regex cannot capture the complexity of various national conventions and rules regarding phone numbers. In any case, though, this issue is not a question of implementation - using `node-phonenumber`, it is easy enough - but rather a question of "do we want that? Do we want to impose a certain format on the API user which might make it a bit harder to use; or do we want to keep the format free, making the phone number suitable for human consumption only?".

**Comment by JirkaChadima** [comment]
Ah, I see. I've used regex as a very simple way of filtering out total nonsense - I imagine it won't cover everything.

Regarding the format itself - From my point of view, it's always better to have consistent data, but it is true that customs in different areas will probably differ - but we can deal with that on a different layer. So I'm saying yes, we should impose a certain format *in the data itself*. Having said that, I can imagine a phone format normalizer in wt-write-api so the users won't be restricted to a single input format.

**Comment by JirkaChadima** [comment]
[This](https://github.com/windingtree/wt-booking-api/commit/4bacdb20d392dc30f618c9b7af401328f65c2693) can probably be used as a resource
